### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by ShitaoChen** [GAIA-vision/GAIA-det#1]
when I pip install -r requirements.txt,there is a problem
ERROR： Could not find a version that satisfies the requirments mmdetection==2.8.8(from versions: none)
ERROR:NO matching distribution found for mmdetection==2.8.0

**Comment by xingyuanbu** [comment]
fixed in https://github.com/GAIA-vision/GAIA-det/pull/2

**Comment by ShitaoChen** [comment]
你好，github的那个问题就是我提的，我看到了你的回复，那我现在应该怎么做的，你说的更新requirements.txt是什么意思啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GAIA-vision/GAIA-det"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月11日(星期天) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GAIA-vision/GAIA-det] pip install -r requirements.txt (#1)





 
Closed #1.
