### ISSUE TITLE
有没有GAIA的交流社区？ 

### ISSUE THREAD

**Issue by raychiu0202** [GAIA-vision/GAIA-det#9]

**Comment by NickChang97** [comment]
Sorry, there is no such platform yet.

**Comment by raychiu0202** [comment]
您好：
        因为我们没有条件去搜集海量不相干数据，也没有大算力平台支持上游模型的训练，请问咱们这个GAIA-det的超网预训练模型开源了吗？我们像基于您上游超网预训练模型测试具体下游检测任务。




致敬！
B.R.
 
RayChiu
Mobile:157 1032 1221   
***@***.***
 
发件人： Qing Chang
发送时间： 2022-04-08 14:02
收件人： GAIA-vision/GAIA-det
抄送： raychiu0202; Author
主题： Re: [GAIA-vision/GAIA-det] 有没有GAIA的交流社区？ (Issue #9)
Sorry, there is no such platform yet.
―

**Comment by NickChang97** [comment]
We already provided the supernet checkpoint trained on COCO and Obj365.

**Comment by raychiu0202** [comment]
> We already provided the supernet checkpoint trained on COCO and Obj365.
Yes, I saw it, but I'm not sure how to run it. Will more detailed documents be provided later? Or I can get your guidance in some way, and then I form a document to share with others

**Comment by raychiu0202** [comment]
Yes, I saw it, but I'm not sure how to run it. Will more detailed documents be provided later? Or I can get your guidance in some way, and then I form a document to share with others

**Comment by raychiu0202** [comment]
> We already provided the supernet checkpoint trained on COCO and Obj365.

Yes, I saw it, but I'm not sure how to run it. Will more detailed documents be provided later? Or I can get your guidance in some way, and then I form a document to share with others

**Comment by NickChang97** [comment]
You can add qq 2292886710

**Comment by NickChang97** [comment]
You can add qq 2292886710
